### ISSUE TITLE
Upgrade to Class Preloader 3.x

### ISSUE THREAD

**Issue by GrahamCampbell** [solid-layer/framework#10]
Hi, I am the current lead on Class Preloader, and I noticed you're currently using an older version. I'd recommend upgrading to 3.x. Let me know if you need any help with the upgrade. ;)

**Comment by daison12006013** [comment]
Nice @GrahamCampbell, I will definitely check that out, thanks.

**Comment by GrahamCampbell** [comment]
I can send a PR if you want.

**Comment by daison12006013** [comment]
yes you could send a PR, It seems you've deleted your recent comment

**Comment by GrahamCampbell** [comment]
It's because the changes I was planning wouldn't work.

**Comment by GrahamCampbell** [comment]
Your compiled.php file specifically tries to load the autoloader again, and won't work if it's already been loaded, so you'll end up with zero files.

**Comment by daison12006013** [comment]
Yeah, I must probably change the logic inside this file, will update later https://github.com/phalconslayer/slayer/blob/dev/bootstrap/autoload.php

**Comment by daison12006013** [comment]
This is done now, and imported using ^3.0, thanks @GrahamCampbell
