### ISSUE TITLE
Integration with Phalcon CI Installer

### ISSUE THREAD

**Issue by sergeyklay** [solid-layer/framework#11]
https://github.com/techpivot/phalcon-ci-installer
It would have saved us from not need work

**Comment by daison12006013** [comment]
Thanks buddy, I'll gonna take a review for it and will integrate asap :+1:

**Comment by daison12006013** [comment]
Buddy @sergeyklay, this is done implemented now [.travis.yml](https://github.com/phalconslayer/framework/blob/master/.travis.yml)
