### ISSUE TITLE
PHP 7 Error

### ISSUE THREAD

**Issue by JCMais** [solid-layer/framework#14]
`
ErrorException in FlattenException.php line 76: Uncaught TypeError: Argument 1 passed to Symfony\Component\Debug\Exception\FlattenException::create() must be an instance of Exception, instance of Error given
` 

This happens because of the changes on error handling that happened on php 7

**Comment by daison12006013** [comment]
@JCMais 

This is weird, can you provide me the last code you got this? is this a v1.4 or the old one?

to check it run `php brood -V`

**Comment by JCMais** [comment]
Yep, this was on 1.4, but I just updated to 1.5 and it still happens.

It happens at the code on https://github.com/phalconslayer/framework/blob/master/src/Clarity/Exceptions/Handler.php#L79

```
    public function handleExceptionError($e)
    {
        $this->render($e);
    }
```

`handleExceptionError` can receive `Error` exceptions, but Symfony `FlattenException` only accepts `Exception` objects: https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Debug/Exception/FlattenException.php#L76 (called from the render method).

I used the following workaround:

``` php
/**
 * Print outs a simple but useful debugging ui.
 *
 * @param $throwable
 * @return void
 */
public function handleExceptionError( $throwable )
{
    if ( $throwable instanceof \Exception ) {

        $exception = $throwable;

    } else {

        static $refl = null;

        if ( null === $refl ) {

            $refl = array();

            foreach ( array( 'file', 'line', 'trace' ) as $prop ) {

                $prop = new \ReflectionProperty( 'Exception', $prop );
                $prop->setAccessible( true );
                $refl[] = $prop;
            }
        }
        $exception = new \Exception( $throwable->getMessage(), $throwable->getCode() );

        foreach ( $refl as $prop ) {
            $prop->setValue( $exception, $throwable->{'get'.$prop->name}() );
        }
    }

    $this->render( $exception );
}
```

Saw it on the following PR for the Symfony component: https://github.com/nicolas-grekas/symfony/blob/b0320967633d5571e211aa80d19e7050a001e096/src/Symfony/Component/Debug/Debug.php#L51

It's basically creating an `Exception` object from an `Error` one.

**Comment by daison12006013** [comment]
Cool, is that work around works well @JCMais ? can you do a pull request on `master` branch and `1.4` branch? since `master` branch was aliased as `v1.5`

also please change `array()` to the new style `[]`

include `if (PHP_VERSION_ID >= 70000) {}`

**Comment by JCMais** [comment]
It's working fine now. You can make the changes, I don't need the credit, since I just copied it from the other PR. :smile:

**Comment by daison12006013** [comment]
okay okay, thanks for the report buddy, this is really a big help :+1:

**Comment by daison12006013** [comment]
@JCMais, I pushed my changes to `master` branch, can you check in your side if works well?

**Comment by JCMais** [comment]
@daison12006013  It's working from what I can see. Thanks!

**Comment by daison12006013** [comment]
cool, I will push it to `1.4` branch. Thanks @JCMais.
