### ISSUE TITLE
Controller logic is broken

### ISSUE THREAD

**Issue by vv3d0x** [solid-layer/framework#18]
Clarity\Support\Phalcon\Mvc\Controller
has broken logic for initialization
beforeExecuteRoute method try to call initialize()
but framework should calls this method only once, in your case it could be twice and more.
**The initialize() method is only called if the ‘beforeExecuteRoute’ event is executed with success. This avoid that application logic in the initializer cannot be executed without authorization.

**Comment by daison12006013** [comment]
@vv3d0x, [Controller@L57](https://github.com/phalconslayer/framework/blob/master/src/Clarity/Support/Phalcon/Mvc/Controller.php#L57)

Do you have a fix for it? would you mind to create a pull request mate?

**Comment by vv3d0x** [comment]
Yes I have a fix, but I would like to talk about, because it has few different solutions and I do not know which one will be the best.

1. My solution is next:  Clarity\Support\Phalcon\Mvc\Controller
`public function beforeExecuteRoute()
    {
        # call the initialize to work with the middleware()
        if (method_exists($this, 'initialize')) {
            $this->initialize();
        }
        $this->middlewareHandler();
    }
`
do not call here **initialize** method, instead I call method **initMiddleware**  (I have renamed it, we can say) and of course I made it in top-level controller
as for me this is the best solution with minimum code changes 
other solutions has more strict defenitions
a: we can separate middleware registering in top-level controller and their handling
using beforeExecuteRoute and initialize,but we still do not need to call initialize inside beforeExecuteRoute, we can register our middleware in beforeExecuteRoute in top-level controller and handle in initialize in base controller
b: we can pass all over beforeExecuteRoute or initialize or onConstruct, but than in all that cases we have to follow a strict steps, and always call parent::methodName(), it will be more agressive and can be brake a login in absolutely different level, which is not well
