### ISSUE TITLE
Is there a way to remove the "Controller" suffix?

### ISSUE THREAD

**Issue by cyberhck** [solid-layer/framework#20]
I know in phalcon we can remove the "Controller" suffix, I'm not sure about that in this project, is there anyway I can get the underlying dispatcher and set it? Since we've got pretty good namespace, we really don't have to worry about having a "Controller" suffix! I'm not requesting to remove it, I'm just requesting the option to remove the suffix.

**Comment by daison12006013** [comment]
Applied under the "dev" branch https://github.com/phalconslayer/slayer/blob/dev/components/Providers/Dispatcher.php#L27
