### ISSUE TITLE
 Uncaught exception 'Phalcon\Http\Response\Exception' with message 'Response was already sent'

### ISSUE THREAD

**Issue by rose1988c** [solid-layer/framework#9]
![image](https://cloud.githubusercontent.com/assets/2977179/14847760/fe3669c6-0c9c-11e6-8135-a0cad599a97c.png)

with version 1.3
phalcon version 2.0.1

**Comment by daison12006013** [comment]
@rose1988c, Can you try the [**dev**](https://github.com/phalconslayer/slayer/archive/dev.zip) branch if it will work on 2.0.1?

**Comment by rkyoku** [comment]
Same error here with Phalcon 2.1.0r (with code that was working fine before I upgraded from 2.0.8).

I will try to debug if I can.

**Comment by rkyoku** [comment]
I confirm it does not bug with 2.0.9

**Comment by daison12006013** [comment]
Thanks @RenaudParis, I'll gonna check it out the 2.1\* version of phalcon, I tried it before but I'm getting an error too.

The package right now works on >=2.0.8 basing it with the travis builds.

**Comment by daison12006013** [comment]
@rose1988c, @RenaudParis, the master (here in framework) branch should be working well now for 2.1.x and 3.0.x phalcon

Try to re-install it again:

```
composer create-project phalconslayer/slayer:dev-dev
```

thanks!
